[package]
name = "ether-packet"
version = "0.1.0"
edition = "2021"

[dependencies]


[features]
std = []

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true
default-features = false